# Generated by Django 4.2.11 on 2024-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField(help_text='in minutes')),
                ('ingredients', models.CharField(max_length=300)),
                ('directions', models.CharField(max_length=500)),
            ],
        ),
    ]
